# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://dpluss.github.io
title: Dpluss
email: dpluss2019@gmail.com
author: Dpluss
description: > # "Write an awesome description for your new site here. 
  Servicii graphic design. Logo, webdesign, pliante, carti de vizita,bannere, pliante.
copyright: 'Copyright &copy; 2019 Dpluss. All Rights Reserved.'
credits: 


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/GraphicDesign.DPluss/
  - title: instagram
    url: https://www.instagram.com/dpluss.design/
  - title: behance
    url: https://www.behance.net/dpluss2019
